/*
  Play melody for AVR Game board
  Press any key to play.

*/

#include <AvrGameBoard.h>

const uint16_t myMelody[] PROGMEM = {
  NOTE_E|OCT_5|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_B|OCT_4|DUR_8, NOTE_C|OCT_5|DUR_8, NOTE_D|OCT_5|DUR_8, NOTE_E|OCT_5|DUR_16, NOTE_D|OCT_5|DUR_16, NOTE_C|OCT_5|DUR_8, 
  NOTE_B|OCT_4|DUR_8, NOTE_A|OCT_4|DUR_8, NOTE_A|OCT_3|DUR_8, NOTE_A|OCT_4|DUR_8, NOTE_C|OCT_5|DUR_8, NOTE_E|OCT_5|DUR_8, NOTE_A|OCT_3|DUR_8, NOTE_D|OCT_5|DUR_8,
  NOTE_C|OCT_5|DUR_8, NOTE_B|OCT_4|DUR_8, NOTE_E|OCT_4|DUR_8, NOTE_G|OCT_4|DUR_8, NOTE_C|OCT_5|DUR_8, NOTE_D|OCT_5|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_E|OCT_5|DUR_8,
  NOTE_E|OCT_3|DUR_8, NOTE_C|OCT_5|DUR_8, NOTE_A|OCT_3|DUR_8, NOTE_A|OCT_4|DUR_8, NOTE_A|OCT_3|DUR_8, NOTE_A|OCT_4|DUR_8, NOTE_A|OCT_3|DUR_8, NOTE_B|OCT_2|DUR_8, 
  NOTE_C|OCT_3|DUR_8, NOTE_D|OCT_3|DUR_8, NOTE_D|OCT_5|DUR_4, NOTE_F|OCT_5|DUR_8, NOTE_A|OCT_5|DUR_8, NOTE_C|OCT_5|DUR_16, NOTE_C|OCT_5|DUR_16, NOTE_G|OCT_5|DUR_8, 
  NOTE_F|OCT_5|DUR_8, NOTE_E|OCT_5|DUR_8, NOTE_C|OCT_3|DUR_8, NOTE_PAUSE|DUR_8,   NOTE_C|OCT_5|DUR_8, NOTE_E|OCT_5|DUR_8, NOTE_A|OCT_4|DUR_16, NOTE_G|OCT_4|DUR_16, 
  NOTE_D|OCT_5|DUR_8, NOTE_C|OCT_5|DUR_8, NOTE_B|OCT_4|DUR_8, NOTE_E|OCT_4|DUR_8, NOTE_B|OCT_4|DUR_8, NOTE_C|OCT_5|DUR_8, NOTE_D|OCT_5|DUR_8, NOTE_G|OCT_4|DUR_8, 
  NOTE_E|OCT_5|DUR_8, NOTE_G|OCT_4|DUR_8, NOTE_C|OCT_5|DUR_8, NOTE_E|OCT_4|DUR_8, NOTE_A|OCT_4|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_A|OCT_4|DUR_4, NOTE_PAUSE|DUR_4, 
  NOTE_E|OCT_5|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_B|OCT_4|DUR_8, NOTE_C|OCT_5|DUR_8, NOTE_D|OCT_5|DUR_8, NOTE_E|OCT_5|DUR_16, NOTE_D|OCT_5|DUR_16, NOTE_C|OCT_5|DUR_8, 
  NOTE_B|OCT_4|DUR_8, NOTE_A|OCT_4|DUR_8, NOTE_A|OCT_3|DUR_8, NOTE_A|OCT_4|DUR_8, NOTE_C|OCT_5|DUR_8, NOTE_E|OCT_5|DUR_8, NOTE_A|OCT_3|DUR_8, NOTE_D|OCT_5|DUR_8,
  NOTE_C|OCT_5|DUR_8, NOTE_B|OCT_4|DUR_8, NOTE_E|OCT_4|DUR_8, NOTE_G|OCT_4|DUR_8, NOTE_C|OCT_5|DUR_8, NOTE_D|OCT_5|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_E|OCT_5|DUR_8,
  NOTE_E|OCT_3|DUR_8, NOTE_C|OCT_5|DUR_8, NOTE_A|OCT_3|DUR_8, NOTE_A|OCT_4|DUR_8, NOTE_A|OCT_3|DUR_8, NOTE_A|OCT_4|DUR_8, NOTE_A|OCT_3|DUR_8, NOTE_B|OCT_2|DUR_8, 
  NOTE_C|OCT_3|DUR_8, NOTE_D|OCT_3|DUR_8, NOTE_D|OCT_5|DUR_4, NOTE_F|OCT_5|DUR_8, NOTE_A|OCT_5|DUR_8, NOTE_C|OCT_5|DUR_16, NOTE_C|OCT_5|DUR_16, NOTE_G|OCT_5|DUR_8, 
  NOTE_F|OCT_5|DUR_8, NOTE_E|OCT_5|DUR_8, NOTE_C|OCT_3|DUR_8, NOTE_PAUSE|DUR_8,   NOTE_C|OCT_5|DUR_8, NOTE_E|OCT_5|DUR_8, NOTE_A|OCT_4|DUR_16, NOTE_G|OCT_4|DUR_16, 
  NOTE_D|OCT_5|DUR_8, NOTE_C|OCT_5|DUR_8, NOTE_B|OCT_4|DUR_8, NOTE_E|OCT_4|DUR_8, NOTE_B|OCT_4|DUR_8, NOTE_C|OCT_5|DUR_8, NOTE_D|OCT_5|DUR_8, NOTE_G|OCT_4|DUR_8, 
  NOTE_E|OCT_5|DUR_8, NOTE_G|OCT_4|DUR_8, NOTE_C|OCT_5|DUR_8, NOTE_E|OCT_4|DUR_8, NOTE_A|OCT_4|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_A|OCT_4|DUR_4, NOTE_PAUSE|DUR_4,
  NOTE_E|OCT_4|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_A|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_C|OCT_4|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_A|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8, 
  NOTE_D|OCT_4|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_Gm|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_B|OCT_3|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_Gm|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8,
  NOTE_C|OCT_4|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_A|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_A|OCT_3|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_A|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8, 
  NOTE_Gm|OCT_3|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_Gm|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_B|OCT_3|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_Gm|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8, 
  NOTE_E|OCT_4|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_A|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_C|OCT_4|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_A|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8, 
  NOTE_D|OCT_4|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_Gm|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_B|OCT_3|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_Gm|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8,
  NOTE_C|OCT_4|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_E|OCT_4|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_A|OCT_4|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_A|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8, 
  NOTE_Gm|OCT_4|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_Gm|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_Gm|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_Gm|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8,
  NOTE_E|OCT_5|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_B|OCT_4|DUR_8, NOTE_C|OCT_5|DUR_8, NOTE_D|OCT_5|DUR_8, NOTE_E|OCT_5|DUR_16, NOTE_D|OCT_5|DUR_16, NOTE_C|OCT_5|DUR_8, 
  NOTE_B|OCT_4|DUR_8, NOTE_A|OCT_4|DUR_8, NOTE_A|OCT_3|DUR_8, NOTE_A|OCT_4|DUR_8, NOTE_C|OCT_5|DUR_8, NOTE_E|OCT_5|DUR_8, NOTE_A|OCT_3|DUR_8, NOTE_D|OCT_5|DUR_8,
  NOTE_C|OCT_5|DUR_8, NOTE_B|OCT_4|DUR_8, NOTE_E|OCT_4|DUR_8, NOTE_G|OCT_4|DUR_8, NOTE_C|OCT_5|DUR_8, NOTE_D|OCT_5|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_E|OCT_5|DUR_8,
  NOTE_E|OCT_3|DUR_8, NOTE_C|OCT_5|DUR_8, NOTE_A|OCT_3|DUR_8, NOTE_A|OCT_4|DUR_8, NOTE_A|OCT_3|DUR_8, NOTE_A|OCT_4|DUR_8, NOTE_A|OCT_3|DUR_8, NOTE_B|OCT_2|DUR_8, 
  NOTE_C|OCT_3|DUR_8, NOTE_D|OCT_3|DUR_8, NOTE_D|OCT_5|DUR_4, NOTE_F|OCT_5|DUR_8, NOTE_A|OCT_5|DUR_8, NOTE_C|OCT_5|DUR_16, NOTE_C|OCT_5|DUR_16, NOTE_G|OCT_5|DUR_8, 
  NOTE_F|OCT_5|DUR_8, NOTE_E|OCT_5|DUR_8, NOTE_C|OCT_3|DUR_8, NOTE_PAUSE|DUR_8,   NOTE_C|OCT_5|DUR_8, NOTE_E|OCT_5|DUR_8, NOTE_A|OCT_4|DUR_16, NOTE_G|OCT_4|DUR_16, 
  NOTE_D|OCT_5|DUR_8, NOTE_C|OCT_5|DUR_8, NOTE_B|OCT_4|DUR_8, NOTE_E|OCT_4|DUR_8, NOTE_B|OCT_4|DUR_8, NOTE_C|OCT_5|DUR_8, NOTE_D|OCT_5|DUR_8, NOTE_G|OCT_4|DUR_8,
  NOTE_E|OCT_5|DUR_8, NOTE_G|OCT_4|DUR_8, NOTE_C|OCT_5|DUR_8, NOTE_E|OCT_4|DUR_8, NOTE_A|OCT_4|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_A|OCT_4|DUR_4, NOTE_PAUSE|DUR_4, 
  NOTE_E|OCT_5|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_B|OCT_4|DUR_8, NOTE_C|OCT_5|DUR_8, NOTE_D|OCT_5|DUR_8, NOTE_E|OCT_5|DUR_16, NOTE_D|OCT_5|DUR_16, NOTE_C|OCT_5|DUR_8, 
  NOTE_B|OCT_4|DUR_8, NOTE_A|OCT_4|DUR_8, NOTE_A|OCT_3|DUR_8, NOTE_A|OCT_4|DUR_8, NOTE_C|OCT_5|DUR_8, NOTE_E|OCT_5|DUR_8, NOTE_A|OCT_3|DUR_8, NOTE_D|OCT_5|DUR_8,
  NOTE_C|OCT_5|DUR_8, NOTE_B|OCT_4|DUR_8, NOTE_E|OCT_4|DUR_8, NOTE_G|OCT_4|DUR_8, NOTE_C|OCT_5|DUR_8, NOTE_D|OCT_5|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_E|OCT_5|DUR_8,
  NOTE_E|OCT_3|DUR_8, NOTE_C|OCT_5|DUR_8, NOTE_A|OCT_3|DUR_8, NOTE_A|OCT_4|DUR_8, NOTE_A|OCT_3|DUR_8, NOTE_A|OCT_4|DUR_8, NOTE_A|OCT_3|DUR_8, NOTE_B|OCT_2|DUR_8, 
  NOTE_C|OCT_3|DUR_8, NOTE_D|OCT_3|DUR_8, NOTE_D|OCT_5|DUR_4, NOTE_F|OCT_5|DUR_8, NOTE_A|OCT_5|DUR_8, NOTE_C|OCT_5|DUR_16, NOTE_C|OCT_5|DUR_16, NOTE_G|OCT_5|DUR_8, 
  NOTE_F|OCT_5|DUR_8, NOTE_E|OCT_5|DUR_8, NOTE_C|OCT_3|DUR_8, NOTE_PAUSE|DUR_8,   NOTE_C|OCT_5|DUR_8, NOTE_E|OCT_5|DUR_8, NOTE_A|OCT_4|DUR_16, NOTE_G|OCT_4|DUR_16, 
  NOTE_D|OCT_5|DUR_8, NOTE_C|OCT_5|DUR_8, NOTE_B|OCT_4|DUR_8, NOTE_E|OCT_4|DUR_8, NOTE_B|OCT_4|DUR_8, NOTE_C|OCT_5|DUR_8, NOTE_D|OCT_5|DUR_8, NOTE_G|OCT_4|DUR_8, 
  NOTE_E|OCT_5|DUR_8, NOTE_G|OCT_4|DUR_8, NOTE_C|OCT_5|DUR_8, NOTE_E|OCT_4|DUR_8, NOTE_A|OCT_4|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_A|OCT_4|DUR_4, NOTE_PAUSE|DUR_4,
  NOTE_E|OCT_4|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_A|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_C|OCT_4|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_A|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8, 
  NOTE_D|OCT_4|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_Gm|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_B|OCT_3|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_Gm|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8,
  NOTE_C|OCT_4|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_A|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_A|OCT_3|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_A|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8, 
  NOTE_Gm|OCT_3|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_Gm|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_B|OCT_3|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_Gm|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8, 
  NOTE_E|OCT_4|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_A|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_C|OCT_4|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_A|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8, 
  NOTE_D|OCT_4|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_Gm|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_B|OCT_3|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_Gm|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8,
  NOTE_C|OCT_4|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_E|OCT_4|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_A|OCT_4|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_A|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8, 
  NOTE_Gm|OCT_4|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_Gm|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_Gm|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8, NOTE_Gm|OCT_2|DUR_8, NOTE_E|OCT_3|DUR_8, 
  MELODY_END 
};


void setup() {
  GameBoard.begin (); 
}

void loop () { 
  if (GameBoard.getPressedKey () != 0) { 
    GameBoard.stopMelody ();
    delay (500);
    GameBoard.playMelody (myMelody);
  }
}  